parameters:
    lightsaml_sp.route.discovery: lightsaml_sp.discovery
    lightsaml.route.login_check: lightsaml_sp.login_check

services:
    lightsaml_sp.username_mapper.simple:
        class: LightSaml\SpBundle\Security\User\SimpleUsernameMapper
        arguments:
            - []

    lightsaml_sp.token_factory:
        class: LightSaml\SpBundle\Security\Authentication\Token\SamlSpTokenFactory

    lightsaml_sp.slo.message_factory:
        class: LightSaml\SpBundle\Model\Protocol\LogoutMessageContextFactory
        arguments:
            - "%lightsaml.own.entity_id%"
            - "@lightsaml.party.idp_entity_descriptor_store"
            - "@lightsaml.own.credential_store"

    http_client:
        class: Http\Adapter\Guzzle6\Client

    lightsaml_sp.idp_data_api.http:
        class: LightSaml\SpBundle\Infrastructure\IdpData\HttpApi
        arguments:
            - "@http_client"
            - "%light_saml_sp.idp_data_metadata_provider.idp_data_url%"

    lightsaml_sp.idp_data_api: "@lightsaml_sp.idp_data_api.http"

    lightsaml_sp.domain_resolver_api.http:
        class: LightSaml\SpBundle\Infrastructure\DomainResolver\HttpApi
        arguments:
            - "@http_client"
            - "@request_stack"
            - "%light_saml_sp.idp_data_metadata_provider.domain_resolver_url%"

    lightsaml_sp.domain_resolver_api: "@lightsaml_sp.domain_resolver_api.http"

    lightsaml_sp.idpdata_metadata_provider:
        class: LightSaml\SpBundle\Metadata\IdpDataMetadataProvider
        arguments:
            - "@lightsaml_sp.idp_data_api"
            - "@lightsaml_sp.domain_resolver_api"
            - "@logger"

    lightsaml.party.idp_entity_descriptor_store.idp_data:
        class: LightSaml\SpBundle\Store\EntityDescriptor\IdpDataEntityDescriptorStore
        arguments:
            - "@lightsaml_sp.idpdata_metadata_provider"

    lightsaml.lightsaml.own_credential_store.idp_data:
        class: LightSaml\SpBundle\Store\Credential\IdpDataCredentialStore
        arguments:
            - "@lightsaml_sp.idp_data_api"
            - "@lightsaml_sp.domain_resolver_api"
            - "@logger"
